### ISSUE TITLE
Stuck on "Launching"

### ISSUE THREAD

**Issue by Tedcharlesbrown** [ZeroSpace-Studios/SpoutRenderstream#6]
Hello, having an issue where the spoutrenderstream workload is stuck on "Launching" in details "Missing Graph".

**Comment by medcelerate** [comment]
Hello, which release version are you using? It is possible that the build process accidentally built the debug version which has this as a feature.

**Comment by Tedcharlesbrown** [comment]
Looks like that was it exactly! I was using v1.9debug. Downloaded v1.9 and worked immediately. Thank you! Amazing work!

**Comment by medcelerate** [comment]
Amazing! Also feel free to share any projects you use it on so we can feature them!
